### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by pandabamboo90** [driggl/jsonapi_errors_handler#20]
Hi @swilgosz ,
Thanks for your great work on this gem.

I found the mistake in your documentation in the **Custom errors mapping** section, when I try to follow the docs.

This line
```
ErrorsMapper.map_errors! # Wrong class name
```

It should be
```
ErrorMapper.map_errors!
```

**Comment by swilgosz** [comment]
Thank you fro reporting this @pandabamboo90 ! I'll fix it in a moment!
