### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by pauljoegeorge** [driggl/jsonapi_errors_handler#24]
Hi @swilgosz 
Thanks for the great work !! 

## issue 
  -  `JsonapiErrorsHandler::Errors::Unauthorized` link is routing to wrong path (::NotFound)
 
## suggestion
  - I have created a PR to fix the issue. Please give a look
  - https://github.com/driggl/jsonapi_errors_handler/pull/23

**Comment by MLHustMaroon** [comment]
noice! what a savior! :heart_eyes:

**Comment by swilgosz** [comment]
Thanks for collaboration! Merged!
