### ISSUE TITLE
Error object status member should be a string?

### ISSUE THREAD

**Issue by tibomogul** [driggl/jsonapi_errors_handler#30]
According to the JSONAPI spec `status: the HTTP status code applicable to this problem, expressed as a string value.`, though it is expressed as `MAY`. Should this be changed to a string? Happy to do a PR if needed.

**Comment by swilgosz** [comment]
I think so. It's an overlook on my side - the generated JSON should match directly the docs. https://jsonapi.org/examples/#error-objects 

It may be that we'll also need some improvements for the `pointer` part at some point. Thanks for checking that!
