### ISSUE TITLE
Rails 6.1's ActiveModel Errors Revamp breaks error response

### ISSUE THREAD

**Issue by KubaSemczuk** [driggl/jsonapi_errors_handler#33]
Rails 6.1 changed how ActiveModel errors are structured ([explanation](https://code.lulalala.com/2020/0531-1013.html), [Pull Request](https://github.com/rails/rails/pull/32313)). It affects `jsonapi_errors_handler` error output.
Error that looked like that:
```
{
  "errors": [
    {
      "status": 422,
      "title": "Invalid request",
      "detail": "can't be blank",
      "source": {
        "pointer": "/data/attributes/magento_id"
      }
    }
  ]
}
```
now looks like that:
```
{
  "errors": [
    {
      "status": 422,
      "title": "Invalid request",
      "detail": null,
      "source":{
        "pointer": "/data/attributes/#<ActiveModel::Error:0x00007fcfe9f8b0e0>"
      }
    }
  ]
}
```
So information what error is about is lost.

**Comment by swilgosz** [comment]
@KubaSemczuk thanks for reporting this! Do you opt for a PR?

**Comment by swilgosz** [comment]
@KubaSemczuk Thanks for reporting this! Do you opt for a PR? :)

**Comment by KubaSemczuk** [comment]
Hi. I'm not sure I'm ready for it skillwise (meaning I'm afraid it would take me ages and I won't have that much free time in next few weeks). I've never contributed to any gem. But I'll take a look at it on the weekend. Can't say I opt for it for now.

**Comment by swilgosz** [comment]
Ok, let me know how it's going!

**Comment by KubaSemczuk** [comment]
Sorry for not getting back to you. Life got in the way and I forgot. I have to say that I won't have time to take care of that in nearest future.

**Comment by swilgosz** [comment]
No worries, added to my todos

**Comment by denialtorres** [comment]
im in rails 6 as well and overwriting the `serializable_hash` method inside `JsonapiErrorsHandler::Errors::Invalid` worked for me 

```ruby
class JsonapiErrorsHandler::Errors::Invalid
  def serializable_hash
    errors_array = []
    errors.to_h&.each do |error|
      errors_array << {
        status: status,
        title: title,
        detail: "#{error[0]} #{error[1]}",
        source: { pointer: "/data/attributes/#{error[0]}" }
      }
    end

    errors_array
  end
end

```

now im getting something like this 

```
{
   :errors=>[
      {
         :status=>422,
         :title=>"Invalid request",
         :detail=>"title can't be blank",
         :source=>{
            :pointer=>"/data/attributes/title"
         }
      },
      {
         :status=>422,
         :title=>"Invalid request",
         :detail=>"content can't be blank",
         :source=>"{
            :"pointer=>"/data/attributes/content"
         }
      },
      {
         :status=>422,
         :title=>"Invalid request",
         :detail=>"slug can't be blank",
         :source=>{
            :pointer=>"/data/attributes/slug"
         }
      }
   ]
}
```
this is the full commit of my project if someone want to see 
https://github.com/denialtorres/api-udemy/commit/3d3ad6cdf187894245c19337dd13d381bb54f9b4

**Comment by swilgosz** [comment]
Resolved in: https://github.com/driggl/jsonapi_errors_handler/commit/2de83389b3d5b9c8a1856ab66c9bae68356e7b8f
