### ISSUE TITLE
Some problems with map_error

### ISSUE THREAD

**Issue by nthngoc277** [driggl/jsonapi_errors_handler#8]
1. Currently, `map_error(e)` returns error class or instance of error class for both cases mapped and unmapped.  So we will never get 500 error in `mapped ||= ::JsonapiErrorsHandler::Errors::StandardError.new` in `handle_error(e)`. 

I suggest that we should return `nil` in case the error does not map, so we can achieve the expected behaviour.
2. `constantize` is not understood without Rails, so we should change to something similar but for Ruby like `Object.const_get(string)`

**Comment by swilgosz** [comment]
Yep, I think we can get rid of the last line: https://github.com/driggl/jsonapi_errors_handler/blob/master/lib/jsonapi_errors_handler.rb#L33

And also we could simplify the 
https://github.com/driggl/jsonapi_errors_handler/blob/master/lib/jsonapi_errors_handler.rb#L17

to not use `Rails.env`
